# Redis Keys
REDIS_KEY_TOT_CITYLIKES = 'tot:c'
REDIS_KEY_TOT_BIZLIKES = 'tot:b'
REDIS_KEY_TOT_LIKES = 'tot:l'
REDIS_KEY_TOT_LISTS = 'tot:li'

REDIS_KEY_CITY_LIKES = 'c:l:'
REDIS_KEY_CITY_LISTS = 'c:li:'
REDIS_KEY_CITY_NAME = 'c:name:'

REDIS_KEY_BIZ_LIKES = 'b:l:'
REDIS_KEY_BIZ_LIKE_CITY = 'bl:c:'
REDIS_KEY_BIZ_TRIES = 'b:t:'
REDIS_KEY_BIZ_LISTS = 'b:li:'

REDIS_KEY_USER_LIKES = 'u:l:'
REDIS_KEY_USER_TRIES = 'u:t:'
REDIS_KEY_USER_FRIENDS = 'u:f:'
REDIS_KEY_USER_DEFLIST = 'u:dli:'
REDIS_KEY_USER_LISTS = 'u:li:'
REDIS_KEY_USER_FOLLOWLIST = 'u:fli:'
REDIS_KEY_USER_TIMESTAMP = 'u:ts:'
REDIS_KEY_USER_NAME = 'u:name:'
REDIS_KEY_USER_TOTAL_MESSAGES = 'u:tm:'
REDIS_KEY_USER_TOTAL_INVITES = 'u:ti:'

REDIS_KEY_LIST = 'li:'
REDIS_KEY_LIST_IMPRESSION = 'li:imp:'
REDIS_KEY_LIST_FOLLOWER = 'li:follow:'
REDIS_KEY_LIST_TIMESTAMP = 'li:ts:'

REDIS_KEY_SYNONYM = '_SYNONYM'
